### ISSUE TITLE
Deliver also ISO image in addition to USB image

### ISSUE THREAD

**Issue by ghost** [erigones/esdc-factory#1]
- Modify factory to create an ISO image along with USB image
- Review, analyze and modify system scripts to look for proper devices and filesystems

**Comment by dn0** [comment]
Implementing creation of an ISO image in esdc-factory is easy. However there are currently 3 reasons why this is not going to be implemented (unless someone explicitly asks for it):

- the upstream scripts for headnode image are not ready for other than USB image (e.g fs-joyent expects a pcfs filesystem);
- the documentation and scripts also expect a persistent `usbkey/config` to be available for writing new server configuration.
