### ISSUE TITLE
Update base zone images to 2016Q4

### ISSUE THREAD

**Issue by dn0** [erigones/esdc-factory#36]
+ upgrade our pkgsrc packages to 2016Q4

**Comment by mbag** [comment]
@dn0  Here are the version of the packages on zones 2015Q4 -> 2016Q4
all:
zabbix-agent-3.0.7 - > zabbix-agent-3.0.9

cfgdb:
zookeeper-3.4.6nb1 -> zookeeper-3.4.8nb1

dns:
powerdns-3.4.9 -> powerdns-4.0.3nb1
postgresql94-client-9.4.10 -> postgresql96-client-9.6.1
powerdns-pgsql-3.4.9 -> powerdns-pgsql-4.0.3

**Comment by dn0** [comment]
@mbag Please check the DB schema requirements for the new version of PowerDNS.

**Comment by mbag** [comment]
@dn0 
In the `records` TABLE:
auth field has default 't' in the PowerDNS schema, but in our initial_migration it is set to false.

Otherwise, seems that DB schema didn't change and the migration to newer version can be done without problems.
