### ISSUE TITLE
/etc/resolv.conf on some service VMs is suboptimal

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-factory#57]
This is /etc/resolv.conf on mon01 right after installation:
```
; generated by /usr/sbin/dhclient-script
nameserver 127.0.0.1
nameserver 10.0.1.123
```
Mon01 does not have any internal DNS resolver, therefore the first `nameserver` directive is inappropriate. It can cause timeouts in name resolution.

This is /etc/resolv.conf on dns01 right after installation:
```
search local
nameserver 127.0.0.1
nameserver 8.8.8.8
```
Here, the second nameserver (google) is inappropriate as it can cause inconsistent name resolution from within the VM.

The rest of service VMs is configured ok.

Jan

**Comment by dn0** [comment]
The fix for a new USB image is simple: https://github.com/erigones/esdc-factory/compare/next...57-fix-resolv.conf

However, I'm afraid that we cannot fix this in existing deployments.
