### ISSUE TITLE
Customize rabbitmq-server systemctl unit file

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-factory#71]
We need to make sure the MQ server is running even there was some external failure (e.g. OOM kill or very slow CPU resulting in start timeouts). This can prevent unexpected "failures" of the management.
It can be achieved by
`cp /usr/lib/systemd/system/rabbitmq-server.service /etc/systemd/system/rabbitmq-server.service`
and adding
`Restart=on-failure` to `[Service]` section.

**Comment by mbag** [comment]
From `man systemd.service`:
> When the death of the process is a result of systemd operation (e.g. service stop or restart), the service will not be restarted.

For the `on-failure` the info is following:
> In this context, a clean exit means an exit code of 0, or one of the signals SIGHUP, SIGINT, SIGTERM or SIGPIPE, and additionally, exit statuses and signals specified in SuccessExitStatus=. If set to on-failure, the service will be restarted when the process exits with a non-zero exit code, is terminated by a signal (including on core dump, but excluding the aforementioned four signals), when an operation (such as service reload) times out, and when the configured watchdog timeout is triggered.

When set to `always` the service behaves like this:
> If set to always, the service will be restarted regardless of whether it exited cleanly or not, got terminated abnormally by a signal, or hit a timeout.

If we choose `always` in case there is something really wrong with the service, it's hard to predict what will forever restarting do to the system. I think that `on-failure` is good choice.

**Comment by dn0** [comment]
@mbag OK lets go with `on-failure`
