### ISSUE TITLE
Add custom postboot SMF user scripts

### ISSUE THREAD

**Issue by YanChii** [erigones/esdc-factory#89]
Add 3 SMF services that will run user scripts at/after boot.
1. pre-network-rc.d
2. pre-vm-rc.d
3. post-vm-rc.d

**pre-network-rc.d**
- starts before networking is up (before `network/physical`)
- location: `/opt/custom/method/pre-network`
- runs scripts from: `/opt/custom/etc/rc.d-pre-network`

**pre-vm-rc.d**
- starts before `svc:/system/zones:default` and `svc:/system/smartdc/vmadmd:default`
- suitable for running iSCSI and other external (Z)FS mounts
- location: `/opt/custom/method/pre-vm`
- runs scripts from: `/opt/custom/etc/rc.d-pre-vm`

**post-vm-rc.d**
- starts after `svc:/system/zones:default` and `svc:/system/smartdc/vmadmd:default`
- suitable for tasks that interact with booted VMs
- equivalent of rc.local
- location: `/opt/custom/method/post-vm`
- runs scripts from: `/opt/custom/etc/rc.d-post-vm`

Proposed names and paths are subject to discussion.

Scripts from `rc.d*` directories are run in alphabetical order at boot (with `start` parameter) and in reverse order during shutdown (with `stop` parameter). Therefore it is recommended to name the scripts with starting number. (e.g. `001-mount-iscsi.sh`).
Only executable files with `.sh` suffix will be run.

**Comment by YanChii** [comment]
1. We should include a sample dummy rc.d script.

2. The mount-iscsi script can be prepared in the `pre-vm-rc.d` as an example.
Example `001-mount-iscsi.sh`:
```
#!/bin/sh -e

mount_zpool()
{
    mypool="$1"
    if ! /usr/sbin/zpool list -Ho name | grep -q "^${mypool}$"; then
        /usr/sbin/zpool import "${mypool}"
    fi
}

start()
{
    /usr/sbin/iscsiadm modify initiator-node -N iqn.2001-03.com.sun:01:e00000000000.6695a9be
    /usr/sbin/iscsiadm add discovery-address 10.20.30.41
    /usr/sbin/iscsiadm add discovery-address 10.20.30.42
    /usr/sbin/iscsiadm modify discovery -t enable
    mount_zpool iscsipool1
    mount_zpool iscsipool2
}

stop()
{
    /usr/sbin/zpool export iscsipool1
    /usr/sbin/zpool export iscsipool2
    /usr/sbin/iscsiadm remove discovery-address 10.20.30.41
    /usr/sbin/iscsiadm remove discovery-address 10.20.30.42
    /usr/sbin/iscsiadm modify discovery -t disable
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  refresh)
    exit 0
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|refresh}"
    exit 1
esac
```

**Comment by YanChii** [comment]
We have an issue here. The `pre-net` scripts are run (obviously) only after `manifest-import`. That leaves us very short time between running `pre-net` and running `network/physical`. Moreover, the `network/physical` is not dependent on `manifest-import` and thus we probably have a race condition here.
We have three options:
1. add these rc manifests into the platform (or at least `pre-net`)
2. change `network/physical` and `ipsec/ipsecalgs` to be dependent on the `manifest-import`
3. leave it like this and believe the delay is sufficient (from my tests, the `manifest-import` starts 2 seconds before `network/physical`. After `manifest-import` is run, there's not a race condition anymore thanks to SMF dependencies that come with `pre-net`.

J.

**Comment by dn0** [comment]
## Naming Things

The idea is great, I would suggest a bit different naming scheme. The file structure:
```
opt
└── custom
    ├── etc
    │   ├── rc-post-vm.d
    │   ├── rc-pre-network.d
    │   └── rc-pre-vm.d
    ├── method
    │   └── postboot-rc
    └── smf
        └── postboot-rc.xml
```

The SMF services could look like this:

- svcs://system/postboot-rc:pre-vm
- svcs://system/postboot-rc:post-vm
- svcs://system/postboot-rc:post-network

One service with 3 instances.

**Comment by YanChii** [comment]
No problem with new naming. 
But my question is if multiple instances of one service can have different dependencies… 
J.

**Comment by YanChii** [comment]
Changed service names to
```
svc:/system/postboot-rc/pre-network
svc:/system/postboot-rc/pre-vmadmd
svc:/system/postboot-rc/post-vmadmd
```

**Comment by YanChii** [comment]
Race condition confirmed. In USB boot, `network/physical` starts before `pre-network`.
We need to add it into the platform.

**Comment by dn0** [comment]
@YanChii Then we should add all services into the PI.
